#!/usr/bin/env bash
echo -e "Scalafmt RUNNING"
scalafmt --git true --diff -c .scalafmt.conf
RESULT=$?
if [ ${RESULT} -ne 0 ]; then
    echo -e "Scalafmt FAILED"
    exit ${RESULT}
fi
echo -e "Scalafmt SUCCEEDED"
exit 0

